In [7]:
import numpy as np

Representation of vector

In [3]:
vectorasList =[1,2,3,4]
vectorasList

[1, 2, 3, 4]

In [4]:
vectorasArr = np.array([3,4,5])
vectorasArr

array([3, 4, 5])

In [5]:
rowvector = np.array([[5,1,2,3]])
rowvector

array([[5, 1, 2, 3]])

In [6]:
columnvector =np.array([[1],[6],[3],[10]])
columnvector

array([[ 1],
       [ 6],
       [ 3],
       [10]])

Arithmetic op

In [12]:
a=np.array([2,5,1,5])
b=np.array([1,4,4,3])
a+b

array([3, 9, 5, 8])

In [13]:
a-b

array([ 1,  1, -3,  2])

In [14]:
a*b

array([ 2, 20,  4, 15])

In [15]:
a/b

array([2.        , 1.25      , 0.25      , 1.66666667])

In [16]:
scalar =2
vectorlist=[1,2,3]
vectorarr=np.array(vectorlist)

In [17]:
scalar*vectorlist

[1, 2, 3, 1, 2, 3]

In [18]:
scalar*vectorarr

array([2, 4, 6])

### Dot product of vectors

In [19]:
a=np.array([3,4,5])
b=np.array([1,2,4])
c=np.array([2,4,5])

Properties - Commutative

In [20]:
coml=np.dot(a,b)
coml

31

In [22]:
comr=np.dot(b,a)
comr

31

Properties - Distributive

In [27]:
disl=np.dot(a,b+c)
disl

78

In [28]:
disr=coml+np.dot(a,c)
disr

78

Magnitude/Norm of vector

In [31]:
from numpy import linalg as lng

In [37]:
a=np.array([1,2,3])
print(lng.norm(a))

3.7416573867739413


Vector projection

In [38]:
b=np.array([2,5,6])
val=(np.dot(a,b)/np.dot(b,b))*b
val

array([0.92307692, 2.30769231, 2.76923077])

Solving linear equations

x=A<sup>-1</sup>.B

In [44]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [45]:
Ainv=lng.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [48]:
B=np.array([2,3])
x=np.dot(Ainv,B)
x

array([-1. ,  1.5])

Checking

In [50]:
np.dot(A,x)

array([2., 3.])

Determinant

In [51]:
m=np.array([[1,2],[5,6]])
print(lng.det(m))

-3.999999999999999


In [56]:
exception=np.array([[1,2],[1,2]])
print(lng.det(exception))

0.0


In [57]:
lng.inv(exception)

LinAlgError: Singular matrix