# Numpy exercises

In [1]:
import numpy as np

In [6]:
integer = np.array([1,24,3,4])
integer

array([ 1, 24,  3,  4])

In [5]:
integer.dtype

dtype('int32')

In [24]:
smallint = np.array(integer,dtype=np.int8)
smallint

array([15, 24,  3,  4], dtype=int8)

In [25]:
integer.nbytes

16

In [26]:
smallint.nbytes

4

In [27]:
integer[0]

15

In [28]:
integer[0]=12

In [29]:
integer

array([12, 24,  3,  4])

In [15]:
integer[0]=15.5
integer

array([15, 24,  3,  4])

In [17]:
floating = np.array([1.2,3.5,6.2])
floating

array([1.2, 3.5, 6.2])

In [19]:
floating.dtype

dtype('float64')

# Multidimensional Arrays

# 2D Array

In [30]:
twod = np.array([[1,2,3],[4,5,6]])
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
twod.ndim

2

In [38]:
twod[0,0]


1

In [37]:
twod[1,2]

6

# 3D Array - 2 (2D array)

In [34]:
threed = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
threed.ndim

3

In [43]:
threed[0,0,0]

1

In [44]:
threed[0,1,2]

6

In [45]:
threed[1,0,0]

7

In [46]:
threed[1,1,2]

12

In [48]:
threed[2,9,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

# Creating Arrays from list

In [49]:
list1 =[1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

# Creating array from list containing numbers & strings 

All the elements gets converted into a string

In [57]:
list2 = [1,"suba","ruba",2]
arr2=np.array(list2)
arr2

array(['1', 'suba', 'ruba', '2'], dtype='<U11')

In [58]:
arr2.dtype

dtype('<U11')

# Creating array from list containing numbers & strings 

All the elements gets converted into a string

In [55]:
list3 =[1,2.33,-1.55,2,4.44,3,5,23]
arr3=np.array(list3)
arr3

array([ 1.  ,  2.33, -1.55,  2.  ,  4.44,  3.  ,  5.  , 23.  ])

In [56]:
arr3.dtype

dtype('float64')

# Creating multidimensional array from list

In [59]:
multlist = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
multarr = np.array(multlist)
multarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Creating array from tuple

In [60]:
tuple1 = (1,2,3,4)
arrt1 = np.array(tuple1)
arrt1

array([1, 2, 3, 4])

In [61]:
arrt1.dtype

dtype('int32')

# Creating arrays from tuples containing numbers & strings

In [62]:
tuple2=(1,"suba")
arrt2 =np.array(tuple2)
arrt2

array(['1', 'suba'], dtype='<U11')

In [63]:
arrt2.dtype

dtype('<U11')

# CREATING ARRAYS USING NUMPY FUNCTIONS

# Intrinsic Numpy array creation

# Integer array using arange

In [64]:
int1 = np.arange(10)
int1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
int2 = np.arange(2,10)
int2

array([2, 3, 4, 5, 6, 7, 8, 9])

# The third parameter STEP used to skip elements by STEP times

## Printing even elements between 2 to 10

In [66]:
int3 = np.arange(2,10,2)
int3

array([2, 4, 6, 8])

# Creating floating point array using linspace

## The third parameter SPLIT used to split the array to SPLIT times

In [69]:
float1 =np.linspace(10,30,5)
float1

array([10., 15., 20., 25., 30.])

# Creating array with random integers using ranint

In [71]:
ranint = np.random.randint(1,20,5)
ranint

array([ 5, 14, 18,  6,  9])

# Creating array with random floating point numbers using rand

## Parameters if 1 => specifies n number of elements between 0 to 1 (1D array)

## if 2 => 2D array

In [73]:
ranfloat = np.random.rand(5)
ranfloat

array([0.95837615, 0.98948412, 0.20328007, 0.10807543, 0.44565942])

In [77]:
ranfloat2d = np.random.rand(5,3)
ranfloat2d

array([[0.06560309, 0.07602412, 0.58571558],
       [0.04221661, 0.30204636, 0.0022305 ],
       [0.96394997, 0.4108598 , 0.33639528],
       [0.25730637, 0.83011619, 0.55281034],
       [0.14666625, 0.58112214, 0.07601877]])

# Creating arrays with constant values 0,1

In [4]:
import numpy as np

In [5]:
arrzero =np.zeros(5)
arrzero

array([0., 0., 0., 0., 0.])

In [6]:
arrones = np.ones(6)
arrones

array([1., 1., 1., 1., 1., 1.])

In [8]:
oneint=np.ones((5,4),dtype=int)
oneint

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Creating array with constant values (Any value)

In [13]:
anyval = np.empty(10,dtype=int)
anyval.fill(24)
anyval

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24])

In [11]:
anyval2d = np.full((4,5),24)
anyval2d


array([[24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24]])

In [15]:
full1d = np.full((4,5),25)
full1d

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [18]:
lin = np.linspace((1,4),(5,7),3,dtype=int)
lin

array([[1, 4],
       [3, 5],
       [5, 7]])

# Shape returns no of elements in each dimension of an array

# Size returns total no of elements in an array

In [19]:
ar1d = np.arange(0,20)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
ar2d = np.linspace((1,4,2),(3,2,3),5)
ar2d

array([[1.  , 4.  , 2.  ],
       [1.5 , 3.5 , 2.25],
       [2.  , 3.  , 2.5 ],
       [2.5 , 2.5 , 2.75],
       [3.  , 2.  , 3.  ]])

In [50]:
ar2d.ndim

2

In [29]:
ar3d = np.full((2,3,2),4)
ar3d

array([[[4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4]]])

In [39]:
np.shape(ar1d)

(20,)

In [33]:
ar2d.shape

(5, 3)

In [34]:
ar3d.shape

(2, 3, 2)

# SIZE

In [35]:
ar1d.size

20

In [36]:
ar2d.size

15

In [38]:
np.size(ar3d)

12

# Adding, Removing and Sorting elements

## ADD using Insert,Append

In [2]:
import numpy as np

In [4]:
insar = np.random.randint(2,20,5)
insar

array([12, 15,  3,  9, 18])

In [5]:
np.insert(insar,3,24)


array([12, 15,  3, 24,  9, 18])

In [6]:
np.append(insar,30)

array([12, 15,  3,  9, 18, 30])

# Deleting element from an array

In [8]:
delar = np.random.randint(10,30,5)
delar

array([15, 23, 18, 21, 24])

In [10]:
np.delete(delar,0)

array([23, 18, 21, 24])

# Sorting elements in an array

In [11]:
sorar = np.random.randint(20,40,10)
sorar

array([36, 20, 22, 26, 25, 38, 34, 39, 26, 39])

In [12]:
np.sort(sorar)

array([20, 22, 25, 26, 26, 34, 36, 38, 39, 39])

In [16]:
arr2d = np.array([[34,12,0],[7,1,5]])
arr2d

array([[34, 12,  0],
       [ 7,  1,  5]])

In [17]:
np.sort(arr2d)

array([[ 0, 12, 34],
       [ 1,  5,  7]])

# Sorting strings in an array

In [13]:
strar = np.array(["suba","ruba","apple","cat","ball"])
strar

array(['suba', 'ruba', 'apple', 'cat', 'ball'], dtype='<U5')

In [14]:
np.sort(strar)

array(['apple', 'ball', 'cat', 'ruba', 'suba'], dtype='<U5')

# Copies and Views

In [18]:
oriar = np.array([1,2,3,4])
oriar

array([1, 2, 3, 4])

In [19]:
newar = oriar
newar

array([1, 2, 3, 4])

In [20]:
print("ori: ",id(oriar))
print("new: ",id(newar))

ori:  2594080114512
new:  2594080114512


In [21]:
newar[0]=5


In [23]:
print("ori: ",oriar)
print("new: ",newar)

ori:  [5 2 3 4]
new:  [5 2 3 4]


## Copy

In [24]:
newcpy=oriar.copy()
newcpy

array([5, 2, 3, 4])

In [25]:
newcpy[0]=10

In [28]:
print("ori: ",oriar)
print("new: ",newcpy)

ori:  [5 2 3 4]
new:  [10  2  3  4]


## View

In [29]:
newvi =oriar.view()
newvi

array([5, 2, 3, 4])

In [30]:
newvi[0]=12

In [31]:
print("ori: ",oriar)
print("new: ",newvi)

ori:  [12  2  3  4]
new:  [12  2  3  4]


## Assignment

In [32]:
assar = oriar
assar

array([12,  2,  3,  4])

In [33]:
assar[0]=15

In [34]:
print("ori: ",oriar)
print("newass: ",assar)

ori:  [15  2  3  4]
newass:  [15  2  3  4]


# Reshaping Arrays

## Using Reshape (single to multidimension)

In [43]:
ar1d = np.arange(0,12)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
re2d=np.reshape(ar1d,(3,4))
re2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
re2derr=np.reshape(ar1d,(3,3))
re2derr

ValueError: cannot reshape array of size 12 into shape (3,3)

In [47]:
re3d = np.reshape(ar1d,(3,2,2))
re3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## Using Reshape (multi dimension to single)

In [52]:
ar2d=np.linspace((3,9),(7,16),4,dtype=int)
ar2d

array([[ 3,  9],
       [ 4, 11],
       [ 5, 13],
       [ 7, 16]])

In [54]:
redar = np.reshape(ar2d,-1)
redar

array([ 3,  9,  4, 11,  5, 13,  7, 16])

In [55]:
print(ar2d.ndim)
print(redar.ndim)

2
1


## Flattening using Flatten(create a copy) 

## Ravel(Creates a view - changes will be reflected to original array)

In [59]:
oar = np.linspace((1,5),(6,10),4,dtype=int)
oar

array([[ 1,  5],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10]])

In [63]:
arflat = oar.flatten()
arravel = oar.ravel()

In [64]:
print("Flatten: ",arflat)
print("Ravel: ",arravel)

Flatten:  [ 1  5  2  6  4  8  6 10]
Ravel:  [ 1  5  2  6  4  8  6 10]


In [65]:
arflat[0]=15
print("ori: ",oar)
print("flatten: ",arflat)

ori:  [[ 1  5]
 [ 2  6]
 [ 4  8]
 [ 6 10]]
flatten:  [15  5  2  6  4  8  6 10]


In [66]:
arravel[0]=12
print("ori: ",oar)
print("Ravel: ",arravel)

ori:  [[12  5]
 [ 2  6]
 [ 4  8]
 [ 6 10]]
Ravel:  [12  5  2  6  4  8  6 10]


# Indexing and Slicing

In [69]:
inarr = np.arange(10)
inarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr3d = np.reshape(np.arange(2*4*3),(2,4,3))
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# Slicing

In [72]:
print(inarr[1:5])
print(inarr[:])
print(inarr[3:])
print(inarr[-3:])

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[7 8 9]


In [75]:
in2d =np.reshape(np.arange(12),(3,4))
in2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
print(in2d[0:,1:])
print("\n")
print(in2d[0,0:])
print("\n")
print(in2d[0:,1])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


[0 1 2 3]


[1 5 9]


In [93]:
print(arr3d[0,1:,1:])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [94]:
print(arr3d[1,0:,2])

[14 17 20 23]


# Indexing

In [84]:
print(inarr[5])
print(in2d[0])

5
[0 1 2 3]


In [92]:
print(arr3d[0])
print("\n")
print(arr3d[0,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[3 4 5]


# Functions for Joining arrays

## Concatenate, Stack, Hstack, Vstack

In [7]:
import numpy as np

In [8]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr2 = np.arange(11,21)
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
concat = np.concatenate((arr1,arr2))
concat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
useresar= np.reshape(np.arange(0,12),(3,4))
useresar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
concat2 = np.linspace((3,1),(7,10),2,dtype=int)
concat2

array([[ 3,  1],
       [ 7, 10]])

In [13]:
useresar2 = np.reshape(np.arange(0,4),(2,2))
useresar2

array([[0, 1],
       [2, 3]])

In [14]:
concat3 = np.concatenate((concat2,useresar2))
concat3

array([[ 3,  1],
       [ 7, 10],
       [ 0,  1],
       [ 2,  3]])

In [15]:
concat4 = np.concatenate((concat2,useresar2),axis=1)
concat4

array([[ 3,  1,  0,  1],
       [ 7, 10,  2,  3]])

In [16]:
hstack1= np.hstack((concat2,useresar2))
hstack1

array([[ 3,  1,  0,  1],
       [ 7, 10,  2,  3]])

In [18]:
vstack1=np.vstack((concat2,useresar2))
vstack1

array([[ 3,  1],
       [ 7, 10],
       [ 0,  1],
       [ 2,  3]])

In [20]:
concat5=np.concatenate((concat2,useresar2),axis=0)
concat5

array([[ 3,  1],
       [ 7, 10],
       [ 0,  1],
       [ 2,  3]])

In [33]:
arr = np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr1 = np.random.randint(1,12,12).reshape(3,4)
arr1

array([[ 3,  8,  4,  1],
       [ 9, 11,  4,  3],
       [ 5,  7,  6,  7]])

In [37]:
star=np.stack((arr,arr1))
star

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 3,  8,  4,  1],
        [ 9, 11,  4,  3],
        [ 5,  7,  6,  7]]])

In [38]:
stas1=np.stack((arr,arr1),axis=1)
stas1

array([[[ 0,  1,  2,  3],
        [ 3,  8,  4,  1]],

       [[ 4,  5,  6,  7],
        [ 9, 11,  4,  3]],

       [[ 8,  9, 10, 11],
        [ 5,  7,  6,  7]]])

In [39]:
stas0=np.stack((arr,arr1),axis=0)
stas0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 3,  8,  4,  1],
        [ 9, 11,  4,  3],
        [ 5,  7,  6,  7]]])

# Splitting Arrays

## Resulting array same shape, No of elements is Divisible by no of splits

## array_split, split, hsplit, vsplit

In [41]:
arr1d = np.arange(3,12)
arr1d

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
sp1d = np.split(arr1d,3)
sp1d

[array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [43]:
sp1d[1]

array([6, 7, 8])

In [44]:
arr2d = np.random.randint(1,100,9).reshape(3,3)
arr2d

array([[45, 70, 95],
       [93, 85,  5],
       [51, 26, 22]])

In [46]:
sp2d=np.array_split(arr2d,3)
sp2d

[array([[45, 70, 95]]), array([[93, 85,  5]]), array([[51, 26, 22]])]

In [47]:
hsp=np.hsplit(arr2d,3)
hsp

[array([[45],
        [93],
        [51]]),
 array([[70],
        [85],
        [26]]),
 array([[95],
        [ 5],
        [22]])]

In [48]:
vsp = np.vsplit(arr2d,3)
vsp

[array([[45, 70, 95]]), array([[93, 85,  5]]), array([[51, 26, 22]])]

In [49]:
spaxis = np.split(arr2d,3,axis=1)
spaxis

[array([[45],
        [93],
        [51]]),
 array([[70],
        [85],
        [26]]),
 array([[95],
        [ 5],
        [22]])]

In [50]:
arspaxis = np.array_split(arr2d,3,axis=0)
arspaxis

[array([[45, 70, 95]]), array([[93, 85,  5]]), array([[51, 26, 22]])]

# Vectorization

## Addition

In [73]:
arr1=np.arange(1,13)
arr2=np.arange(3,15)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [74]:
arr1+arr2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [75]:
np.sum((arr1,arr2))

180

In [76]:
np.add(arr1,arr2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

## Subtraction

In [77]:
np.subtract(arr2,arr1)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
arr1-arr2

array([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2])

## Multiply

In [79]:
np.multiply(arr1,arr2)

array([  3,   8,  15,  24,  35,  48,  63,  80,  99, 120, 143, 168])

In [80]:
arr1*arr2

array([  3,   8,  15,  24,  35,  48,  63,  80,  99, 120, 143, 168])

In [81]:
arr1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## Divide

In [82]:
np.divide(arr2,arr1)

array([3.        , 2.        , 1.66666667, 1.5       , 1.4       ,
       1.33333333, 1.28571429, 1.25      , 1.22222222, 1.2       ,
       1.18181818, 1.16666667])

In [83]:
arr2/arr1

array([3.        , 2.        , 1.66666667, 1.5       , 1.4       ,
       1.33333333, 1.28571429, 1.25      , 1.22222222, 1.2       ,
       1.18181818, 1.16666667])

## Mod

In [84]:
np.mod(arr2,arr1)

array([0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [85]:
arr2%arr1

array([0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

## Exponentiation

In [86]:
arr2**2

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196],
      dtype=int32)

In [87]:
np.power(arr2,2)

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196],
      dtype=int32)

## Sqrt

In [89]:
np.sqrt(arr2)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128, 3.74165739])

### Perform arithmetic operations on arrays of different shape using broadcasting

#### In this case smaller shaped array can be expanded to match the large array by using simple arrays

In [91]:
arr2 = np.arange(0,3)
arr2

array([0, 1, 2])

In [93]:
arr3 = np.random.randint(0,100,12).reshape(4,3)
arr3

array([[73, 41, 28],
       [21, 67, 48],
       [84, 41, 95],
       [57, 73, 31]])

### Match the last dimensions of both arrays (if same then match first dimension of both arrays) if first dimensions do not match then expand upto the largest first dimension 

### ex : A (3,3) B(1,3) => expand B(3,3) by taking B as
### [1,2,3
###  1,2,3
###  1,2,3]   


### if B is [1,2,3]

In [94]:
arr3+arr2

array([[73, 42, 30],
       [21, 68, 50],
       [84, 42, 97],
       [57, 74, 33]])

In [96]:
arr4 = np.arange(0,2)
arr4

array([0, 1])

In [97]:
arr4+arr3

ValueError: operands could not be broadcast together with shapes (2,) (4,3) 

# Aggregate functions

In [115]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [116]:
arr1.sum()

450

In [120]:
arr2 = np.arange(1,5)

In [121]:
np.prod(arr2)

24

In [109]:
np.average(arr1)

50.0

In [110]:
arr1.min()

10

In [111]:
arr1.max()

90

In [112]:
arr1.mean()

50.0

In [113]:
arr1.std()

25.81988897471611

In [124]:
arr2d = np.arange(10,130,10).reshape(3,4)
arr2d

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [125]:
arr2d.sum()

780

## Axis = 1 Row

In [129]:
arr2d.sum(axis=1)

array([100, 260, 420])

In [131]:
arr2d.mean(axis=1)

array([ 25.,  65., 105.])

In [132]:
arr2d.prod(axis=1)

array([   240000,  16800000, 118800000])

## Axis = 0 Column

In [128]:
arr2d.sum(axis=0)

array([150, 180, 210, 240])

In [133]:
arr2d.mean(axis=0)

array([50., 60., 70., 80.])

In [134]:
arr2d.prod(axis=0)

array([ 45000, 120000, 231000, 384000])

# Get Unique elements and their count

In [135]:
arr=np.array([1,2,1,3,2,4,3,5,6,4,7])

In [136]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [138]:
np.unique(arr,return_counts=True,return_index=True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  3,  5,  7,  8, 10], dtype=int64),
 array([2, 2, 2, 2, 1, 1, 1], dtype=int64))

In [149]:
arr2d =np.array([[1,2,1],[1,2,1],[3,4,3]])

In [150]:
np.unique(arr2d)

array([1, 2, 3, 4])

In [151]:
np.unique(arr2d,return_index=True,return_counts=True)

(array([1, 2, 3, 4]),
 array([0, 1, 6, 7], dtype=int64),
 array([4, 2, 2, 1], dtype=int64))

### Column wise unique elements

In [152]:
np.unique(arr2d,axis=1)

array([[1, 2],
       [1, 2],
       [3, 4]])

### Row wise unique elements

In [153]:
np.unique(arr2d,axis=0,return_index=True,return_counts=True)

(array([[1, 2, 1],
        [3, 4, 3]]),
 array([0, 2], dtype=int64),
 array([2, 1], dtype=int64))

# Transpose 

## Transpose has 2 parammeters 

1) array

2) axis(optional)

## transpose(axis(1,0)=>incase of 2D array || axis(1,0,2)=>incase of 3D array)

For 2D array ,

    [[0,1,2],[3,4,5]] => shape(2,3) => indexed as 2->0 , 3->1
    
    So when using transpose if you put (1,0) in place of axis which specifies it will result in a 3X2 matrix



In [156]:
arr2d = np.arange(0,12).reshape(3,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
np.transpose(arr2d,(1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [163]:
ar2d = np.arange(0,6).reshape(3,2)
ar2d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [169]:
tr2d = np.transpose(ar2d,(1,0))
tr2d

array([[0, 2, 4],
       [1, 3, 5]])

In [172]:
tr2d.shape

(2, 3)

## Transpose using 3D array

In [173]:
thd = np.arange(24).reshape(2,3,4)
thd

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [181]:
thd.transpose(2,1,0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## Move axis

Move axis takes 3 parameters,

1)arrayname

2)source (index of original array to be changed)

3)destination (index to place the source index)

ex;


3D array =>  

              array([[[ 0,  1,  2,  3],
   
                    [ 4,  5,  6,  7],
       
                    [ 8,  9, 10, 11]],
                   
                   [[12, 13, 14, 15],
                    
                    [16, 17, 18, 19],
                    
                    [20, 21, 22, 23]]]) => has dimension (2,3,4) => indexed as 2->0 ,3->1, 4->2

specifying np.moveaxis(arr,0,-1) => index 0(2) has gone to index 2(2) 

The resultant array will have shape as (3,4,2)



In [196]:
arr3d = np.arange(24).reshape(2,3,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [197]:
np.moveaxis(arr3d,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

## Swapaxes

Swap axes 2 parameters

1) array

2) index to swap -> i1

3) index with which i1 has to be swapped

ex : 3D array with dimensions (2,3,4)
    
    after swapaxes(0,2) => 2 is swapped with 4 => resulting shape (4,3,2)

In [198]:
np.swapaxes(arr3d,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

# Reversing an array

In [199]:
arr1d =np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
arr1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Using flip

Flip takes in parameter axis:

1) axis=0 => flip vertically

2) axis=1 => flip horizontally


In [229]:
np.flip(arr1d)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [230]:
arr2d = np.arange(0,9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

For 2D array:
    
    if dimension(3,2) => indexed as (0,1)
    
    flip(arr,0) => flip the array wrt 3(row)
    flip(arr,1) => flip the array wrt 2(col)
    
    

In [240]:
np.flip(arr2d)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [233]:
np.flip(arr2d,0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [232]:
np.flip(arr2d,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [234]:
arr3d = np.arange(12).reshape(2,3,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [235]:
np.flip(arr3d,0)

array([[[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

In [236]:
np.flip(arr3d,1)

array([[[ 4,  5],
        [ 2,  3],
        [ 0,  1]],

       [[10, 11],
        [ 8,  9],
        [ 6,  7]]])

In [237]:
np.flip(arr3d,2)

array([[[ 1,  0],
        [ 3,  2],
        [ 5,  4]],

       [[ 7,  6],
        [ 9,  8],
        [11, 10]]])

In [238]:
np.flip(arr3d)

array([[[11, 10],
        [ 9,  8],
        [ 7,  6]],

       [[ 5,  4],
        [ 3,  2],
        [ 1,  0]]])

For 3D array:
    
    if dimension (2,3,4) => indexed as (0,1,2)
    
    flip(arr,0) => flip the array with respect to 2(at index 0)
    flip(arr,1) => flip the array with respect to 3(at index 1 => row)
    flip(arr,2) => flip the array with respect to 4(at index 2 => col)