# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1d = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2d= np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

# Create a 3-dimensional Numpy array using np.array()
arr3d = np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                   
                  [[2,5,3],
                   [1,9,4],
                   [3,2,7]],
                  
                  [[1,45,21],
                  [5,10,7],
                  [6,76,23]],
                  
                  [[3,6,1],
                   [4,1,9],
                   [5,6,3]]
                 ]
                )

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1d.shape,arr1d.ndim,arr1d.dtype,arr1d.size,type(arr1d)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
arr2d.shape,arr2d.ndim,arr2d.dtype,arr2d.size,type(arr2d)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
arr3d.shape,arr3d.ndim,arr3d.dtype,arr3d.size,type(arr3d)

((4, 3, 3), 3, dtype('int32'), 36, numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df1 = pd.DataFrame(arr1d)
df2 = pd.DataFrame(arr2d)
df2

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,101,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,size=(7,2))

array([[5, 3],
       [0, 7],
       [8, 4],
       [4, 8],
       [7, 9],
       [1, 0],
       [0, 5]])

In [17]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size=(3,5))

array([[0.70522471, 0.59518866, 0.72913515, 0.07201679, 0.6343723 ],
       [0.0750651 , 0.24257819, 0.59041469, 0.69780802, 0.91771734],
       [0.80040791, 0.64087446, 0.31023977, 0.55926235, 0.19351488]])

In [21]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand = np.random.randint(0,10,size=(4,6))
rand

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is? 

## the numbers are same because of seed

In [22]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randnum = np.random.randint(1,10,size=(3,7))
randnum

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [24]:
# Find the unique numbers in the array you just created
unique = np.unique(randnum)

In [25]:
# Find the 0'th index of the latest array you created
unique[0]

1

In [26]:
# Get the first 2 rows of latest array you created
randnum[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
randnum[0:2,0:1]

array([[9],
       [5]])

In [28]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arrnum = np.random.randint(0,10,size=(3,5))
newones = np.ones((3,5))

In [33]:
# Add the two arrays together
added = np.add(arrnum,newones)
added,added.shape

(array([[ 7.,  8.,  3.,  1.,  4.],
        [ 2.,  8.,  4.,  2.,  6.],
        [ 6., 10.,  4.,  6.,  2.]]),
 (3, 5))

In [34]:
# Create another array of ones of shape (5, 3)
anotherones = np.ones((5,3))

In [37]:
# Try add the array of ones and the other most recent array together
np.add(added,anotherones)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [38]:
# Try add the array of ones and the other most recent array together
np.add(added,anotherones.T)

array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

When you try the last cell, it produces an error. Why do think this is?

## it is because the dimensions of two array does not match

How would you fix it?

## take transpose any one array so that dimensions are same

In [39]:
# Create another array of ones of shape (3, 5)
anoanotherone = np.ones((3,5))

In [42]:
# Subtract the new array of ones from the other most recent array
sub = np.subtract(added,anoanotherone)
sub,sub.shape

(array([[6., 7., 2., 0., 3.],
        [1., 7., 3., 1., 5.],
        [5., 9., 3., 5., 1.]]),
 (3, 5))

In [44]:
# Multiply the ones array with the latest array
mul = np.multiply(anoanotherone,sub)
mul,mul.shape

(array([[6., 7., 2., 0., 3.],
        [1., 7., 3., 1., 5.],
        [5., 9., 3., 5., 1.]]),
 (3, 5))

In [47]:
# Take the latest array to the power of 2 using '**'
mul**2

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [49]:
# Do the same thing with np.square()
sq = np.square(mul)
sq,sq.shape

(array([[36., 49.,  4.,  0.,  9.],
        [ 1., 49.,  9.,  1., 25.],
        [25., 81.,  9., 25.,  1.]]),
 (3, 5))

In [50]:
# Find the mean of the latest array using np.mean()
sq.mean()

21.6

In [51]:
# Find the maximum of the latest array using np.max()
sq.max()

81.0

In [52]:
# Find the minimum of the latest array using np.min()
sq.min()

0.0

In [53]:
# Find the standard deviation of the latest array
sq.std()

22.8

In [54]:
# Find the variance of the latest array
sq.var()

519.84

In [57]:
# Reshape the latest array to (3, 5, 1)
reshaped = sq.reshape(3,5,1)
reshaped,reshaped.shape

(array([[[36.],
         [49.],
         [ 4.],
         [ 0.],
         [ 9.]],
 
        [[ 1.],
         [49.],
         [ 9.],
         [ 1.],
         [25.]],
 
        [[25.],
         [81.],
         [ 9.],
         [25.],
         [ 1.]]]),
 (3, 5, 1))

In [58]:
# Transpose the latest array
reshaped.T

array([[[36.,  1., 25.],
        [49., 49., 81.],
        [ 4.,  9.,  9.],
        [ 0.,  1., 25.],
        [ 9., 25.,  1.]]])

What does the transpose do?

## switches the dimensions (3,5,1) => (1,5,3)

In [59]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand1 = np.random.randint(0,10,size=(3,3))
rand2 = np.random.randint(0,10,size=(3,2))


In [60]:
# Perform a dot product on the two newest arrays you created
rand1.dot(rand2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [61]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand3 = np.random.randint(0,10,size=(4,3))
rand4 =np.random.randint(0,10,size=(4,3))

In [62]:
# Perform a dot product on the two newest arrays you created
rand3.dot(rand4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it? \

## by taking transpose

In [64]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

rand3.dot(rand4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [65]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand3,rand4

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]]),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [66]:
# Compare the two arrays with '>'
rand3 > rand4

array([[False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [67]:
# Compare the two arrays with '>='
rand3 >= rand4

array([[False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [86]:
# Find which elements of the first array are greater than 7
for i in range(4):
    for j in range(3):
        if( rand3[i][j] > 7):
            print("[",i,"],","[",j,"], : ",rand3[i][j])

[ 0 ], [ 1 ], :  8
[ 1 ], [ 0 ], :  8


In [87]:
# Which parts of each array are equal? (try using '==')
for i in range(4):
    for j in range(i+1,4):
        boolean = (rand3[i]==rand3[j])
        if(boolean.all()):
            print(i," : ",rand[i]," " ,j," : ",rand[j])

In [83]:
for i in range(4):
    for j in range(i+1,4):
        boolean = (rand3[i]>=rand3[j])
        if(boolean.all()):
            print(i," : ",rand[i]," " ,j," : ",rand[j])

0  :  [6 3 7 4 6 9]   3  :  [5 1 4 0 9 5]
2  :  [7 2 5 4 1 7]   3  :  [5 1 4 0 9 5]


In [88]:
# Sort one of the arrays you just created in ascending order
sorted_arr = np.sort(rand3)
sorted_arr

array([[0, 6, 8],
       [0, 7, 8],
       [2, 7, 7],
       [0, 2, 7]])

In [90]:
# Sort the indexes of one of the arrays you just created
rand3

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]])

In [92]:
argsort = np.argsort(rand3,axis=0)
argsort

array([[0, 1, 1],
       [3, 2, 2],
       [2, 3, 3],
       [1, 0, 0]], dtype=int64)

In [93]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand3)

1

In [95]:
# Find the index with the minimum value in one of the arrays you've created
rand3

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]])

In [96]:
np.argmin(rand3)

0

In [97]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand3,axis=1)

array([1, 0, 0, 1], dtype=int64)

In [98]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand3,axis=0)

array([0, 1, 1], dtype=int64)

In [101]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.17773212, -0.41038331,  1.17971634, -0.89820794,  0.83479542],
       [ 0.29656138, -1.03782988, -0.07580375,  0.97296353,  0.79559546],
       [ 1.49543425,  0.33818125,  3.37229625, -0.92039081, -0.39863839]])

In [100]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly = np.linspace(1,100,10)
evenly

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.