# Numpy exercises

In [1]:
import numpy as np

In [6]:
integer = np.array([1,24,3,4])
integer

array([ 1, 24,  3,  4])

In [5]:
integer.dtype

dtype('int32')

In [24]:
smallint = np.array(integer,dtype=np.int8)
smallint

array([15, 24,  3,  4], dtype=int8)

In [25]:
integer.nbytes

16

In [26]:
smallint.nbytes

4

In [27]:
integer[0]

15

In [28]:
integer[0]=12

In [29]:
integer

array([12, 24,  3,  4])

In [15]:
integer[0]=15.5
integer

array([15, 24,  3,  4])

In [17]:
floating = np.array([1.2,3.5,6.2])
floating

array([1.2, 3.5, 6.2])

In [19]:
floating.dtype

dtype('float64')

# Multidimensional Arrays

# 2D Array

In [30]:
twod = np.array([[1,2,3],[4,5,6]])
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
twod.ndim

2

In [38]:
twod[0,0]


1

In [37]:
twod[1,2]

6

# 3D Array - 2 (2D array)

In [34]:
threed = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threed

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
threed.ndim

3

In [43]:
threed[0,0,0]

1

In [44]:
threed[0,1,2]

6

In [45]:
threed[1,0,0]

7

In [46]:
threed[1,1,2]

12

In [48]:
threed[2,9,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

# Creating Arrays from list

In [49]:
list1 =[1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

# Creating array from list containing numbers & strings 

All the elements gets converted into a string

In [57]:
list2 = [1,"suba","ruba",2]
arr2=np.array(list2)
arr2

array(['1', 'suba', 'ruba', '2'], dtype='<U11')

In [58]:
arr2.dtype

dtype('<U11')

# Creating array from list containing numbers & strings 

All the elements gets converted into a string

In [55]:
list3 =[1,2.33,-1.55,2,4.44,3,5,23]
arr3=np.array(list3)
arr3

array([ 1.  ,  2.33, -1.55,  2.  ,  4.44,  3.  ,  5.  , 23.  ])

In [56]:
arr3.dtype

dtype('float64')

# Creating multidimensional array from list

In [59]:
multlist = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
multarr = np.array(multlist)
multarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Creating array from tuple

In [60]:
tuple1 = (1,2,3,4)
arrt1 = np.array(tuple1)
arrt1

array([1, 2, 3, 4])

In [61]:
arrt1.dtype

dtype('int32')

# Creating arrays from tuples containing numbers & strings

In [62]:
tuple2=(1,"suba")
arrt2 =np.array(tuple2)
arrt2

array(['1', 'suba'], dtype='<U11')

In [63]:
arrt2.dtype

dtype('<U11')

# CREATING ARRAYS USING NUMPY FUNCTIONS

# Intrinsic Numpy array creation

# Integer array using arange

In [64]:
int1 = np.arange(10)
int1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
int2 = np.arange(2,10)
int2

array([2, 3, 4, 5, 6, 7, 8, 9])

# The third parameter STEP used to skip elements by STEP times

## Printing even elements between 2 to 10

In [66]:
int3 = np.arange(2,10,2)
int3

array([2, 4, 6, 8])

# Creating floating point array using linspace

## The third parameter SPLIT used to split the array to SPLIT times

In [69]:
float1 =np.linspace(10,30,5)
float1

array([10., 15., 20., 25., 30.])

# Creating array with random integers using ranint

In [71]:
ranint = np.random.randint(1,20,5)
ranint

array([ 5, 14, 18,  6,  9])

# Creating array with random floating point numbers using rand

## Parameters if 1 => specifies n number of elements between 0 to 1 (1D array)

## if 2 => 2D array

In [73]:
ranfloat = np.random.rand(5)
ranfloat

array([0.95837615, 0.98948412, 0.20328007, 0.10807543, 0.44565942])

In [77]:
ranfloat2d = np.random.rand(5,3)
ranfloat2d

array([[0.06560309, 0.07602412, 0.58571558],
       [0.04221661, 0.30204636, 0.0022305 ],
       [0.96394997, 0.4108598 , 0.33639528],
       [0.25730637, 0.83011619, 0.55281034],
       [0.14666625, 0.58112214, 0.07601877]])

# Creating arrays with constant values 0,1

In [4]:
import numpy as np

In [5]:
arrzero =np.zeros(5)
arrzero

array([0., 0., 0., 0., 0.])

In [6]:
arrones = np.ones(6)
arrones

array([1., 1., 1., 1., 1., 1.])

In [8]:
oneint=np.ones((5,4),dtype=int)
oneint

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Creating array with constant values (Any value)

In [13]:
anyval = np.empty(10,dtype=int)
anyval.fill(24)
anyval

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24])

In [11]:
anyval2d = np.full((4,5),24)
anyval2d


array([[24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24]])

In [15]:
full1d = np.full((4,5),25)
full1d

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [18]:
lin = np.linspace((1,4),(5,7),3,dtype=int)
lin

array([[1, 4],
       [3, 5],
       [5, 7]])

# Shape returns no of elements in each dimension of an array

# Size returns total no of elements in an array

In [19]:
ar1d = np.arange(0,20)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
ar2d = np.linspace((1,4,2),(3,2,3),5)
ar2d

array([[1.  , 4.  , 2.  ],
       [1.5 , 3.5 , 2.25],
       [2.  , 3.  , 2.5 ],
       [2.5 , 2.5 , 2.75],
       [3.  , 2.  , 3.  ]])

In [50]:
ar2d.ndim

2

In [29]:
ar3d = np.full((2,3,2),4)
ar3d

array([[[4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4]]])

In [39]:
np.shape(ar1d)

(20,)

In [33]:
ar2d.shape

(5, 3)

In [34]:
ar3d.shape

(2, 3, 2)

# SIZE

In [35]:
ar1d.size

20

In [36]:
ar2d.size

15

In [38]:
np.size(ar3d)

12

# Adding, Removing and Sorting elements

## ADD using Insert,Append

In [2]:
import numpy as np

In [4]:
insar = np.random.randint(2,20,5)
insar

array([12, 15,  3,  9, 18])

In [5]:
np.insert(insar,3,24)


array([12, 15,  3, 24,  9, 18])

In [6]:
np.append(insar,30)

array([12, 15,  3,  9, 18, 30])

# Deleting element from an array

In [8]:
delar = np.random.randint(10,30,5)
delar

array([15, 23, 18, 21, 24])

In [10]:
np.delete(delar,0)

array([23, 18, 21, 24])

# Sorting elements in an array

In [11]:
sorar = np.random.randint(20,40,10)
sorar

array([36, 20, 22, 26, 25, 38, 34, 39, 26, 39])

In [12]:
np.sort(sorar)

array([20, 22, 25, 26, 26, 34, 36, 38, 39, 39])

In [16]:
arr2d = np.array([[34,12,0],[7,1,5]])
arr2d

array([[34, 12,  0],
       [ 7,  1,  5]])

In [17]:
np.sort(arr2d)

array([[ 0, 12, 34],
       [ 1,  5,  7]])

# Sorting strings in an array

In [13]:
strar = np.array(["suba","ruba","apple","cat","ball"])
strar

array(['suba', 'ruba', 'apple', 'cat', 'ball'], dtype='<U5')

In [14]:
np.sort(strar)

array(['apple', 'ball', 'cat', 'ruba', 'suba'], dtype='<U5')

# Copies and Views

In [18]:
oriar = np.array([1,2,3,4])
oriar

array([1, 2, 3, 4])

In [19]:
newar = oriar
newar

array([1, 2, 3, 4])

In [20]:
print("ori: ",id(oriar))
print("new: ",id(newar))

ori:  2594080114512
new:  2594080114512


In [21]:
newar[0]=5


In [23]:
print("ori: ",oriar)
print("new: ",newar)

ori:  [5 2 3 4]
new:  [5 2 3 4]


## Copy

In [24]:
newcpy=oriar.copy()
newcpy

array([5, 2, 3, 4])

In [25]:
newcpy[0]=10

In [28]:
print("ori: ",oriar)
print("new: ",newcpy)

ori:  [5 2 3 4]
new:  [10  2  3  4]


## View

In [29]:
newvi =oriar.view()
newvi

array([5, 2, 3, 4])

In [30]:
newvi[0]=12

In [31]:
print("ori: ",oriar)
print("new: ",newvi)

ori:  [12  2  3  4]
new:  [12  2  3  4]


## Assignment

In [32]:
assar = oriar
assar

array([12,  2,  3,  4])

In [33]:
assar[0]=15

In [34]:
print("ori: ",oriar)
print("newass: ",assar)

ori:  [15  2  3  4]
newass:  [15  2  3  4]


# Reshaping Arrays

## Using Reshape (single to multidimension)

In [43]:
ar1d = np.arange(0,12)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
re2d=np.reshape(ar1d,(3,4))
re2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
re2derr=np.reshape(ar1d,(3,3))
re2derr

ValueError: cannot reshape array of size 12 into shape (3,3)

In [47]:
re3d = np.reshape(ar1d,(3,2,2))
re3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## Using Reshape (multi dimension to single)

In [52]:
ar2d=np.linspace((3,9),(7,16),4,dtype=int)
ar2d

array([[ 3,  9],
       [ 4, 11],
       [ 5, 13],
       [ 7, 16]])

In [54]:
redar = np.reshape(ar2d,-1)
redar

array([ 3,  9,  4, 11,  5, 13,  7, 16])

In [55]:
print(ar2d.ndim)
print(redar.ndim)

2
1


## Flattening using Flatten(create a copy) 

## Ravel(Creates a view - changes will be reflected to original array)

In [59]:
oar = np.linspace((1,5),(6,10),4,dtype=int)
oar

array([[ 1,  5],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10]])

In [63]:
arflat = oar.flatten()
arravel = oar.ravel()

In [64]:
print("Flatten: ",arflat)
print("Ravel: ",arravel)

Flatten:  [ 1  5  2  6  4  8  6 10]
Ravel:  [ 1  5  2  6  4  8  6 10]


In [65]:
arflat[0]=15
print("ori: ",oar)
print("flatten: ",arflat)

ori:  [[ 1  5]
 [ 2  6]
 [ 4  8]
 [ 6 10]]
flatten:  [15  5  2  6  4  8  6 10]


In [66]:
arravel[0]=12
print("ori: ",oar)
print("Ravel: ",arravel)

ori:  [[12  5]
 [ 2  6]
 [ 4  8]
 [ 6 10]]
Ravel:  [12  5  2  6  4  8  6 10]


# Indexing and Slicing

In [69]:
inarr = np.arange(10)
inarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr3d = np.reshape(np.arange(2*4*3),(2,4,3))
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# Slicing

In [72]:
print(inarr[1:5])
print(inarr[:])
print(inarr[3:])
print(inarr[-3:])

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[7 8 9]


In [75]:
in2d =np.reshape(np.arange(12),(3,4))
in2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
print(in2d[0:,1:])
print("\n")
print(in2d[0,0:])
print("\n")
print(in2d[0:,1])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


[0 1 2 3]


[1 5 9]


In [93]:
print(arr3d[0,1:,1:])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [94]:
print(arr3d[1,0:,2])

[14 17 20 23]


# Indexing

In [84]:
print(inarr[5])
print(in2d[0])

5
[0 1 2 3]


In [92]:
print(arr3d[0])
print("\n")
print(arr3d[0,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[3 4 5]
